In [1]:
import numpy as np

In [3]:
a = np.array([1,2])

b = np.transpose(a)



In [4]:
b

array([[1, 3],
       [2, 4]])

In [16]:
np.multiply.outer(a,b)

array([[[[ 1,  3],
         [ 2,  4]],

        [[ 2,  6],
         [ 4,  8]]],


       [[[ 3,  9],
         [ 6, 12]],

        [[ 4, 12],
         [ 8, 16]]]])

In [17]:
np.tensordot(a,b,axes = 2)

array(29)

In [22]:
d = np.array([[1,2],[3,4]])
e = np.array([[2,8],[8,16]])

In [36]:
a = np.array([1,2])

np.tile(d[:,0].transpose(),(1,3))

array([[1, 2, 1, 2, 1, 2]])

In [45]:
np.stack((d[:,0],d[:,1],d[:,1]),axis=1)

array([[1, 2, 2],
       [2, 6, 6]])

In [48]:
print(np.repeat(d,3,axis=1))

np.tile(d,3)

[[1 1 1 2 2 2]
 [2 2 2 6 6 6]]


array([[1, 2, 1, 2, 1, 2],
       [2, 6, 2, 6, 2, 6]])